CHnages to make building a request easier
KalbiProject/kalbi pull request #139
Opened 2022-07-26 19:53 UTC by hyperioxx

2022-07-26 20:01 UTC, peterdonald3 commented
Looks okay apart from the fmt. statement

2022-07-27 10:25 UTC, hyperioxx commented
> Looks okay apart from the fmt. statement


@peterdonald3 Yeah missed that, now been removed !

2022-07-30 21:36 UTC, DeWarner requested changes

2022-07-30 21:36 UTC, DeWarner commented on kalbi.go
> +		fmt.Print(message)
```suggestion
		log.Log.Info(message)
```

2022-07-30 21:39 UTC, DeWarner commented on kalbi.go
> +
```suggestion
```

2022-07-30 21:40 UTC, DeWarner commented on kalbi.go
>  	"github.com/KalbiProject/kalbi/log"
```suggestion
	"github.com/KalbiProject/kalbi/log"
```

2022-07-30 21:42 UTC, DeWarner commented on kalbi.go
> +		fmt.Print(message)
```suggestion
		log.Log.Info(message)
```

2022-07-30 21:44 UTC, DeWarner submitted a review, later dismissed

2022-08-07 17:41 UTC, peterdonald3 approved these changes
Approved, but needs a new issue raising for rogue fmt.Println()s

2022-08-07 17:41 UTC, peterdonald3 commented on examples/basicUAC/main.go
>  	fmt.Println(string(event.GetSipMessage().Src))
to delete

2022-08-07 17:41 UTC, peterdonald3 commented on examples/basicUAC/main.go
>  	fmt.Println(string(event.GetSipMessage().Src))
\ and import

2022-08-12 11:24 UTC, DeWarner approved these changes

2022-08-12 11:27 UTC, merged